# based on https://github.com/travis-ci/travis-ci/blob/master/.github/stale.yml

daysUntilStale: 90
daysUntilClose: 1

exemptLabels:
  - important

staleLabel: wontfix
markComment: >
  Thanks for contributing to this issue. As it has been 90 days since the last activity, we are automatically closing the issue in 24 hours. This is often because the request was already solved in some way and it just wasn't updated or it's no longer applicable. If that's not the case, please do feel free to either reopen this issue or open a new one. We'll gladly take a look again!

limitPerRun: 30

only: issues
