version: 2
jobs:
  build:
    docker:
      - image: cavariux/nimgl
    steps:
      - checkout
      # installs build tools and opengl dev
      # adds github to dowload submodules
      - run: |
          mkdir -p ~/.ssh
          mv .circleci/ssh_config ~/.ssh/config
          git submodule update --init --recursive
      # build
      - run: nimble test
