version: 2
jobs:
  build:
    docker:
      - image: cavariux/nimgl
    steps:
      - checkout
      # adds github to dowload submodules
      - run: |
          mkdir -p ~/.ssh
          mv .circleci/ssh_config ~/.ssh/config
          git submodule update --init --recursive
      # build
      - run: nimble test
  build_alpine:
    docker:
      - image: cavariux/nimgl:alpine
    steps:
      - checkout
      # adds github to dowload submodules
      - run: |
          mkdir -p ~/.ssh
          mv .circleci/ssh_config ~/.ssh/config
          git submodule update --init --recursive
      # build
      - run: nimble test
workflows:
  version: 2
  build_and_test:
      jobs:
        - build
        - build_alpine
